- hosts: all
  become: true
  vars_files:
    - group_vars/global.yml
  roles:
    - docker
    - anchore-database
    - anchore-catalog
    - anchore-analyzer
    - anchore-policy
    - anchore-queue
    - anchore-api
