---
- name: "Install Anchore DB"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ anchore_database_docker_name }}"
    image: "{{ anchore_database_docker_image }}:{{ anchore_database_docker_tag }}"
    volumes:
      - anchore-volume:/var/lib/postgresql/data
    env:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - name: ansible
    restart_policy: always
    expose:
      - "{{ anchore_database_docker_port }}"
  tags:
    - install-anchore