---
- name: "Install Anchore Analyzer"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ anchore_analyzer_docker_name }}"
    image: "{{ anchore_analyzer_docker_image }}:{{ anchore_analyzer_docker_tag }}"
    volumes:
      - /analysis_scratch
    networks:
      - name: ansible
    restart_policy: always
    expose:
      - "{{ anchore_analyzer_docker_port }}"
    env:
      ANCHORE_ENDPOINT_HOSTNAME: analyzer
      ANCHORE_ADMIN_PASSWORD: foobar
      ANCHORE_DB_HOST: db
      ANCHORE_DB_PASSWORD: mysecretpassword
    command: ["anchore-manager", "service", "start", "analyzer"]
  tags:
    - install-anchore
    