---
- name: "Install Anchore Catalog"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ anchore_catalog_docker_name }}"
    image: "{{ anchore_catalog_docker_image }}:{{ anchore_catalog_docker_tag }}"
    networks:
      - name: ansible
    restart_policy: always
    expose:
      - "{{ anchore_catalog_docker_port }}"
    env:
      ANCHORE_ENDPOINT_HOSTNAME: catalog
      ANCHORE_ADMIN_PASSWORD: foobar
      ANCHORE_DB_HOST: db
      ANCHORE_DB_PASSWORD: mysecretpassword
    command: ["anchore-manager", "service", "start", "catalog"]
  tags:
    - install-anchore