---
- name: "Install Anchore Api"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ anchore_api_docker_name }}"
    image: "{{ anchore_api_docker_image }}:{{ anchore_api_docker_tag }}"
    networks:
      - name: ansible
    restart_policy: always
    ports:
      - "{{ anchore_api_docker_port }}:8228"
    env:
      ANCHORE_ENDPOINT_HOSTNAME: api
      ANCHORE_ADMIN_PASSWORD: foobar
      ANCHORE_DB_HOST: db
      ANCHORE_DB_PASSWORD: mysecretpassword
    command: ["anchore-manager", "service", "start", "apiext"]
  tags:
    - install-anchore