---
- name: "Install Anchore Policy"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ anchore_policy_docker_name }}"
    image: "{{ anchore_policy_docker_image }}:{{ anchore_policy_docker_tag }}"
    networks:
      - name: ansible
    restart_policy: always
    expose:
      - "{{ anchore_policy_docker_port }}"
    env:
      ANCHORE_ENDPOINT_HOSTNAME: policy-engine
      ANCHORE_ADMIN_PASSWORD: foobar
      ANCHORE_DB_HOST: db
      ANCHORE_DB_PASSWORD: mysecretpassword
    command: ["anchore-manager", "service", "start", "policy_engine"]
  tags:
    - install-anchore